import Link from "next/link";
import { z } from "zod";
import { ChangeBadge } from "@/components/badge";
import { EmptyState } from "@/components/empty-state";
import { formatDate, integer } from "@/lib/format";
import { getChanges, getFilings, getLatestFiling } from "@/lib/data";

export const metadata = { title: "Portfolio Changes" };
const schema = z.string().regex(/^\d{10}-\d{2}-\d{6}$/);
export default async function ChangesPage({ searchParams }: { searchParams: Promise<{ filing?: string }> }) { const selected = (await searchParams).filing; const filings = (await getFilings()).filter((item) => item.status === "processed" && item.form_type.startsWith("13F")); const latest = await getLatestFiling(); const filing = selected && schema.safeParse(selected).success ? filings.find((item) => item.accession_number === selected) : latest; const changes = filing ? await getChanges(filing.id) : []; return <><div className="mb-7"><p className="mb-2 text-xs font-bold uppercase text-emerald-700">Quantity-based comparison</p><h1 className="text-2xl font-semibold">Portfolio changes</h1><p className="mt-2 text-sm text-zinc-500">Each filing compared with the immediately preceding comparable report.</p></div>{filings.length ? <div className="mb-5 flex flex-wrap gap-2" aria-label="Select filing">{filings.map((item) => <Link key={item.id} href={`/changes?filing=${item.accession_number}`} className={`border px-3 py-2 text-sm ${filing?.id === item.id ? "border-zinc-950 bg-zinc-950 text-white" : "border-zinc-300 bg-white"}`}>{formatDate(item.report_period)}</Link>)}</div> : null}{changes.length ? <div className="overflow-x-auto border border-zinc-200 bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-zinc-200 bg-zinc-50 text-xs uppercase text-zinc-500"><tr><th className="px-4 py-3">Issuer</th><th className="px-4 py-3">Security</th><th className="px-4 py-3 text-right">Previous</th><th className="px-4 py-3 text-right">Current</th><th className="px-4 py-3 text-right">Quantity change</th><th className="px-4 py-3">Classification</th></tr></thead><tbody className="divide-y divide-zinc-100">{changes.toSorted((a,b) => Math.abs(b.quantity_change)-Math.abs(a.quantity_change)).map((item) => <tr key={item.id}><td className="px-4 py-3 font-medium">{item.issuer_name}</td><td className="px-4 py-3 text-zinc-500">{item.put_call || "Shares"} · {item.title_of_class}</td><td className="px-4 py-3 text-right tabular-nums">{integer.format(item.previous_quantity)}</td><td className="px-4 py-3 text-right tabular-nums">{integer.format(item.current_quantity)}</td><td className="px-4 py-3 text-right tabular-nums">{`${item.quantity_change > 0 ? "+" : ""}${integer.format(item.quantity_change)}`}</td><td className="px-4 py-3"><ChangeBadge value={item.classification} /></td></tr>)}</tbody></table></div> : <EmptyState title="No comparison available" detail="At least one processed 13F is required. The first imported filing will classify every disclosed position as NEW." />}</>; }
