import Link from "next/link";
import { ExternalLink } from "lucide-react";
import { EmptyState } from "@/components/empty-state";
import { formatDate } from "@/lib/format";
import { getFilings } from "@/lib/data";

export const metadata = { title: "Filing History" };
export default async function FilingsPage() { const filings = await getFilings(); return <><div className="mb-7"><p className="mb-2 text-xs font-bold uppercase text-emerald-700">Official record</p><h1 className="text-2xl font-semibold">Filing history</h1><p className="mt-2 text-sm text-zinc-500">Tracked SEC submissions and ingestion status.</p></div>{filings.length ? <div className="overflow-x-auto border border-zinc-200 bg-white"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b border-zinc-200 bg-zinc-50 text-xs uppercase text-zinc-500"><tr><th className="px-4 py-3">Form</th><th className="px-4 py-3">Filed</th><th className="px-4 py-3">Report period</th><th className="px-4 py-3">Accession</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Source</th></tr></thead><tbody className="divide-y divide-zinc-100">{filings.map((filing) => <tr key={filing.id}><td className="px-4 py-3 font-semibold">{filing.form_type}</td><td className="px-4 py-3">{formatDate(filing.filing_date)}</td><td className="px-4 py-3">{formatDate(filing.report_period)}</td><td className="px-4 py-3 font-mono text-xs">{filing.accession_number}</td><td className="px-4 py-3"><span title={filing.error_message ?? undefined} className="rounded bg-zinc-100 px-2 py-1 text-xs font-semibold uppercase">{filing.status.replace("_", " ")}</span></td><td className="px-4 py-3"><span className="flex gap-3">{filing.status === "processed" && filing.form_type.startsWith("13F") ? <Link className="font-semibold underline underline-offset-4" href={`/filings/${filing.accession_number}`}>Portfolio</Link> : null}<a className="inline-flex items-center gap-1 font-semibold underline underline-offset-4" href={filing.sec_url} target="_blank" rel="noreferrer">SEC <ExternalLink className="size-3" /></a></span></td></tr>)}</tbody></table></div> : <EmptyState title="No filings discovered" detail="Run poll_sec.py or the historical importer to populate the filing timeline." />}</>; }

